=== JRIP24/dam/m04/xml/exercici_8.dtd
<!ELEMENT TVSCHEDULE (CHANNEL+,canal?)>
<!ATTLIST TVSCHEDULE NAME NMTOKENS #REQUIRED>
<!ELEMENT CHANNEL (BANNER, DAY+)>
<!ATTLIST CHANNEL CHAN NMTOKENS #REQUIRED>
<!ELEMENT BANNER (#PCDATA)>
<!ELEMENT DAY (DATE, (HOLIDAY | PROGRAMSLOT+))>
<!ELEMENT DATE (#PCDATA)>
<!ELEMENT HOLIDAY (#PCDATA)>
<!ELEMENT PROGRAMSLOT (TIME, TITLE,DESCRIPTION?)>
<!ATTLIST PROGRAMSLOT VTR CDATA #IMPLIED>
<!ELEMENT TIME (#PCDATA)>
<!ELEMENT TITLE (#PCDATA)>
<!ATTLIST TITLE RATING NMTOKENS #IMPLIED>
<!ATTLIST TITLE LANGUAGE NMTOKENS #IMPLIED>
<!ELEMENT DESCRIPTION (#PCDATA)>
<!ELEMENT canal (#PCDATA)>

=== JRIP24/dam/m04/M04_UF1_NF1_exercici_8_part_2.xml
<?xml version="1.0"?>
<!DOCTYPE TVSCHEDULE SYSTEM "exercici_8.dtd">
<TVSCHEDULE NAME="Viking2">
	<CHANNEL CHAN="patito feo">
		<BANNER> el banner 2 </BANNER>
		<DAY>
			<DATE> la data 2 </DATE>
			<HOLIDAY> les vacances 2 </HOLIDAY>
		</DAY>
		<DAY>
			<DATE> la data 2 </DATE>
			<PROGRAMSLOT VTR="no estoy">
				<TIME> el temps 2 </TIME>
				<TITLE> el titol 2</TITLE>
				<DESCRIPTION> la descripcio 1</DESCRIPTION>
			</PROGRAMSLOT>
		</DAY>
	</CHANNEL>
	<canal> el canal 2 </canal>
</TVSCHEDULE>

=== JRIP24/dam/m04/M04_UF1_NF1_exercici_8_part_1.xml
<?xml version="1.0"?>
<!DOCTYPE TVSCHEDULE SYSTEM "exercici_8.dtd">
<TVSCHEDULE NAME="Viking1">
	<CHANNEL CHAN="patito feo">
		<BANNER> el banner 1 </BANNER>
		<DAY>
			<DATE> la data 1 </DATE>
			<HOLIDAY> les vacances 1 </HOLIDAY>
		</DAY>
		<DAY>
			<DATE> la data 1 </DATE>
			<PROGRAMSLOT VTR="no estoy">
				<TIME> el temps 1 </TIME>
				<TITLE> el titol 1</TITLE>
				<DESCRIPTION> la descripcio 1</DESCRIPTION>
			</PROGRAMSLOT>
		</DAY>
	</CHANNEL>
	<CHANNEL CHAN="patito malo">
		<BANNER> el banner 1 </BANNER>
		<DAY>
			<DATE> la data 1 </DATE>
			<HOLIDAY> les vacances 1 </HOLIDAY>
		</DAY>
		<DAY>
			<DATE> la data 1 </DATE>
			<PROGRAMSLOT VTR="">
				<TIME> el temps 1 </TIME>
				<TITLE> el titol 1</TITLE>
				<DESCRIPTION> la descripcio 1</DESCRIPTION>
			</PROGRAMSLOT>
			<PROGRAMSLOT VTR="no estoy 2">
				<TIME> el temps 1 </TIME>
				<TITLE RATING="rat" LANGUAGE="ru"> el titol 1</TITLE>
			</PROGRAMSLOT>
		</DAY>
	</CHANNEL>
</TVSCHEDULE>
