=== JRIP24/dam/m04/examen_part_1/Earth_Alliance.dtd
<!ELEMENT babylon5 (bandol)>
<!ELEMENT bandol (nau+)>
<!ATTLIST bandol nom ID #REQUIRED>
<!ELEMENT nau (subclasse, tipus, longitud, tonelatge, capacitat_humana, capacitat_naus, propulsio, abast, gravetat_artificial?, data_alta, noms)>
<!ATTLIST nau classe ID #REQUIRED>

<!ELEMENT subclasse (#PCDATA)>
<!ATTLIST subclasse classeMare CDATA #IMPLIED>

<!ELEMENT tipus (#PCDATA)>

<!ELEMENT longitud (#PCDATA)>
<!ATTLIST longitud unitat (metres | polzades) "metres" >

<!ELEMENT tonelatge (#PCDATA)>
<!ATTLIST tonelatge unitat CDATA #FIXED "milions de tonelades metriques" >

<!ELEMENT capacitat_humana (tripulacio, tropes?)>
<!ELEMENT tripulacio (#PCDATA)>
<!ELEMENT tropes (#PCDATA)>

<!ELEMENT capacitat_naus (caces, transports_tropes?)>
<!ELEMENT caces (#PCDATA)>
<!ELEMENT transports_tropes (#PCDATA)>

<!ELEMENT propulsio (numero_de_motors_impulsio, motors_impulsio, reactors+, potencia_standart, potencia_militar, unitat_de_mesura_potencia)>
<!ELEMENT numero_de_motors_impulsio (#PCDATA)>
<!ELEMENT motors_impulsio (#PCDATA)>
<!ELEMENT reactors (#PCDATA)>
<!ATTLIST reactors numero NMTOKENS "1">
<!ELEMENT potencia_standart (#PCDATA)>
<!ELEMENT potencia_militar (#PCDATA)>
<!ELEMENT unitat_de_mesura_potencia (#PCDATA)>

<!ELEMENT abast ((quantitat, unitat_de_mesura )| quantitat_2)>
<!ELEMENT quantitat (#PCDATA)>
<!ELEMENT unitat_de_mesura (#PCDATA)>
<!ELEMENT quantitat_2 (#PCDATA)>
<!ATTLIST quantitat_2 unitat_de_mesura CDATA #IMPLIED>

<!ELEMENT gravetat_artificial (#PCDATA)>
<!ATTLIST gravetat_artificial llengua ( es | en |fi | sv) "en">

<!ELEMENT data_alta (( (dia,mes,any) | any ))>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT any (#PCDATA)>

<!ELEMENT noms (nom*)>
<!ATTLIST noms coneguts CDATA #REQUIRED>
<!ELEMENT nom (#PCDATA)>

=== JRIP24/dam/m04/examen_part_1/Earth_Alliance.xml
<?xml version="1.0"?>
<!DOCTYPE babylon5 SYSTEM "Earth_Alliance.dtd">
<babylon5>
	<bandol nom="Earth_Alliance">
		<nau classe="Omega_Class_destroyer">
			<subclasse classeMare="Omega">Omega</subclasse>
			<tipus>destructor</tipus>
			<longitud unitat="metres">1717,3</longitud>
			<tonelatge unitat="milions de tonelades metriques">44,6</tonelatge>
			<capacitat_humana>
				<tripulacio>850</tripulacio>
				<tropes>18000</tropes>
			</capacitat_humana>
			<capacitat_naus>
				<caces>36</caces>
				<transports_tropes>80</transports_tropes>
			</capacitat_naus>
			<propulsio>
				<numero_de_motors_impulsio>4</numero_de_motors_impulsio>
				<motors_impulsio>KD-1105 Proxima</motors_impulsio>
				<reactors numero="4">General Fusion 650</reactors>
				<potencia_standart>3943</potencia_standart>
				<potencia_militar>101408</potencia_militar>
				<unitat_de_mesura_potencia>Terawatts</unitat_de_mesura_potencia>
			</propulsio>
			<abast>
				<quantitat>18</quantitat>
				<unitat_de_mesura>mesos</unitat_de_mesura>
			</abast>
			<gravetat_artificial llengua="en">false</gravetat_artificial>
			<data_alta>
				<dia>1</dia>
				<mes>1</mes>
				<any>2249</any>
			</data_alta>
			<noms coneguts="32">
				<nom>AES Acheron</nom>
				<nom>AES Achilles</nom>
				<nom>AES Agamemnon</nom>
				<nom>AES Agrippa</nom>
				<nom>AES Excalibur</nom>
				<nom>AES Hermes</nom>
				<nom>AES Juno</nom>
				<nom>AES Nimrod</nom>
				<nom>AES Orion</nom>
			</noms>
		</nau>
		<nau classe="OmegaX_Class_destroyer">
			<subclasse classeMare="Omega-X">Advanced</subclasse>
			<tipus>destructor</tipus>
			<longitud unitat="metres">1720</longitud>
			<tonelatge unitat="milions de tonelades metriques">50</tonelatge>
			<capacitat_humana>
				<tripulacio>850</tripulacio>
				<tropes>18000</tropes>
			</capacitat_humana>
			<capacitat_naus>
				<caces>36</caces>
				<transports_tropes>80</transports_tropes>
			</capacitat_naus>
			<propulsio>
				<numero_de_motors_impulsio>4</numero_de_motors_impulsio>
				<motors_impulsio>KD-1105 Proxima</motors_impulsio>
				<reactors numero="4">General Fusion 650</reactors>
				<potencia_standart>3943</potencia_standart>
				<potencia_militar>101408</potencia_militar>
				<unitat_de_mesura_potencia>Terawatts</unitat_de_mesura_potencia>
			</propulsio>
			<abast>
				<quantitat>18</quantitat>
				<unitat_de_mesura>mesos</unitat_de_mesura>
			</abast>
			<gravetat_artificial llengua="en">false</gravetat_artificial>
			<data_alta>
				<any>2261</any>
			</data_alta>
			<noms coneguts="0">
			</noms>
		</nau>
		<nau classe="Hyperion_type_heavy_cruiser">
			<subclasse classeMare="Hyperion">Roosevelt, Hyperion, Midwinter</subclasse>
			<tipus>creuer pesat</tipus>
			<longitud unitat="metres">1187,7</longitud>
			<tonelatge unitat="milions de tonelades metriques">9,1</tonelatge>
			<capacitat_humana>
				<tripulacio>356</tripulacio>
				<tropes>200</tropes>
			</capacitat_humana>
			<capacitat_naus>
				<caces>6</caces>
			</capacitat_naus>
			<propulsio>
				<numero_de_motors_impulsio>3</numero_de_motors_impulsio>
				<motors_impulsio>J-64D Optimal</motors_impulsio>
				<reactors numero="3">General Fusion 420-B</reactors>
				<potencia_standart>325</potencia_standart>
				<potencia_militar>5633</potencia_militar>
				<unitat_de_mesura_potencia>Terawatts</unitat_de_mesura_potencia>
			</propulsio>
			<abast>
				<quantitat_2 unitat_de_mesura="mesos">12</quantitat_2>
			</abast>
			<gravetat_artificial llengua="en">false</gravetat_artificial>
			<data_alta>
				<dia>1</dia>
				<mes>1</mes>
				<any>2237</any>
			</data_alta>
			<noms coneguts="7">
				<nom>AES Hyperion</nom>
				<nom>AES Lexington</nom>
				<nom>AES Prometheus</nom>
				<nom>AES Trafalgar</nom>
			</noms>
		</nau>
	</bandol>
</babylon5>
